// This allows TypeScript to pick up the magic constants that are
// auto-generated by Forge's Webpack plugin which tells the
// app where to look for the Webpack-bundled app code
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const SPLASH_WINDOW_WEBPACK_ENTRY: string;
declare const THREADING_WINDOW_WEBPACK_ENTRY: string;
